econ250_2025:
  outputs:
    dev:
      dataset: adatsiv_us
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: econ250-2025
      threads: 2
      type: bigquery
  target: dev
my-bigquery-db:
  outputs:
    dev:
      dataset: adatsiv_us
      method: oauth
      project: econ250-2025
      threads: 4
      type: bigquery
  target: dev
