version: 2

sources:
  - name: adatsiv_us
    schema: adatsiv_us
    tables:
      - name: week5_hits
        description: "Hit-level log data"
      - name: week5_web_visits
        description: "Visit-level data"
      - name: week5_web_transactions
        description: "Transaction-level data"
models:
  - name: fct_landing_page
    description: "The first page hit per visit (landing page)"
    columns:
      - name: visitId
        description: "Unique ID for a visit"
      - name: page
        description: "First page visited during the session"
